### PR TITLE
Add CSS to Docs

### PR DESCRIPTION
**Pull request by devarshishimpi**
Add CSS to Docs

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@ericspring08

**Comment by MrKrishnaAgarwal** [comment]
Can you contribute this to mine

https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi

**Comment by devarshishimpi** [comment]
> Can you contribute this to mine
> 
> https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages

@MrKrishnaAgarwal 

Hi, Sure, will make PR

**Comment by MrKrishnaAgarwal** [comment]
> > Can you contribute this to mine
> > https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages
> 
> @MrKrishnaAgarwal
> 
> Hi, Sure, will make PR

Thanks a lot
I'll merge as soon as possible, in my repo.

**Comment by ericspring08** [comment]
> > > Can you contribute this to mine
> > > https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages
> > 
> > 
> > @MrKrishnaAgarwal
> > Hi, Sure, will make PR
> 
> Thanks a lot I'll merge as soon as possible, in my repo.

Hey, please don't copy other peoples code and call your own. Please give credit to the original creator of the code.

**Comment by devarshishimpi** [comment]
> > > > Can you contribute this to mine
> > > > https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages
> > > 
> > > 
> > > @MrKrishnaAgarwal
> > > Hi, Sure, will make PR
> > 
> > 
> > Thanks a lot I'll merge as soon as possible, in my repo.
> 
> Hey, please don't copy other peoples code and call your own. Please give credit to the original creator of the code.

Makes sense.

@MrKrishnaAgarwal Hey, I won't contribute to yours since you have actually copied @ericspring08 project and that too without forking it.

Thank You

**Comment by devarshishimpi** [comment]
Also, @ericspring08 Can You please merge this PR as well?

**Comment by ericspring08** [comment]
> Also, @ericspring08 Can You please merge this PR as well?
Working on It.

**Comment by ericspring08** [comment]
Looks good

**Comment by devarshishimpi** [comment]
Your welcome again 😊 Happy to Contribute. Will be adding more languages!!!

**Comment by ericspring08** [comment]
Thanks!

**Comment by devarshishimpi** [comment]
Also @MrKrishnaAgarwal Stealing Codes and creating duplicates is hurtful, Kindly learn to give credits to the original creators.

**Comment by ericspring08** [comment]
Please share this repo if possible and give it a ⭐ !

**Comment by devarshishimpi** [comment]
> > > Can you contribute this to mine
> > > https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages
> > 
> > 
> > @MrKrishnaAgarwal
> > Hi, Sure, will make PR
> 
> Thanks a lot I'll merge as soon as possible, in my repo.

@ericspring08 I am extremely sorry that I almost saw it as a genuine project and contribute it, But yes, the projects is your and supported by the community!!! Such Code Stealers should be stopped, making original code and taking efforts in Issues and PRs is a big task.

**Comment by ericspring08** [comment]
> Also, @ericspring08 Is It Alright in CSS.md file that I have added Stone CSS??? https://github.com/devarshishimpi/Stone-CSS-Website

Yeah thats fine its a genuine project.

**Comment by ericspring08** [comment]
> > > > Can you contribute this to mine
> > > > https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages
> > > 
> > > 
> > > @MrKrishnaAgarwal
> > > Hi, Sure, will make PR
> > 
> > 
> > Thanks a lot I'll merge as soon as possible, in my repo.
> 
> @ericspring08 I am extremely sorry that I almost saw it as a genuine project and contribute it, But yes, the projects is your and supported by the community!!! Such Code Stealers should be stopped, making original code and taking efforts in Issues and PRs is a big task.

Thanks!

**Comment by devarshishimpi** [comment]
> > Also, @ericspring08 Is It Alright in CSS.md file that I have added Stone CSS??? https://github.com/devarshishimpi/Stone-CSS-Website
> 
> Yeah thats fine its a genuine project.

Thanks

**Comment by devarshishimpi** [comment]
@ericspring08 sent you an email as well

**Comment by ericspring08** [comment]
@devarshishimpi My discord is GreekGodOfComputerScience#6804

**Comment by devarshishimpi** [comment]
> @devarshishimpi My discord is GreekGodOfComputerScience#6804

@ericspring08  Alright!! You will get an friend request from lil.dev ( I don't remember the # but I will send you friend request )

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi and @ericspring08 

I didn't completely copied your project, I just stole your idea, I wrote the contributing.md on my own and I also added workflows and templates for pr and issues,

but due to your request I have deleted my repo and If you wish I'll contribute my work and improvements I did in mine to your repo.

My apologies , all my other projects are genuine, you can check them.

**Comment by ericspring08** [comment]
> @devarshishimpi and @ericspring08
> 
> I didn't completely copied your project, I just stole your idea, I wrote the contributing.md on my own and I also added workflows and templates for pr and issues, my Jekyll theme was different too.
> 
> but due to your request I have deleted my repo and If you wish I'll contribute my work and improvements I did in mine to your repo.
> 
> My apologies , all my other projects are genuine, you can check them.

Thank You!

**Comment by MrKrishnaAgarwal** [comment]
> > @devarshishimpi and @ericspring08
> > I didn't completely copied your project, I just stole your idea, I wrote the contributing.md on my own and I also added workflows and templates for pr and issues, my Jekyll theme was different too.
> > but due to your request I have deleted my repo and If you wish I'll contribute my work and improvements I did in mine to your repo.
> > My apologies , all my other projects are genuine, you can check them.
> 
> Thank You!

No worries!
Instead let's work together on another project, you got good skills.

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi and @ericspring08

My Discord: KrishnaAgarwal#3748

**Comment by devarshishimpi** [comment]
> @devarshishimpi and @ericspring08
> 
> I didn't completely copied your project, I just stole your idea, I wrote the contributing.md on my own and I also added workflows and templates for pr and issues, my Jekyll theme was different too.
> 
> but due to your request I have deleted my repo and If you wish I'll contribute my work and improvements I did in mine to your repo.
> 
> My apologies , all my other projects are genuine, you can check them.

Alright

**Comment by devarshishimpi** [comment]
> @devarshishimpi My discord is GreekGodOfComputerScience#6804

@ericspring08 Have sent friend req

**Comment by MrKrishnaAgarwal** [comment]
> @ericspring08 Have sent friend req

**KrishnaAgarwal#3748**

**Pull request merged**
