### PR TITLE
added greetings when someone makes pr or issue

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
@ericspring08 
@devarshishimpi

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
This will work, Tested 💯

**Comment by devarshishimpi** [comment]
@ericspring08 Those links refer to his profile, not sure if it should be added.

**Comment by devarshishimpi** [comment]
@ericspring08 
image

**Comment by devarshishimpi** [comment]
Also, The github secret token is missing.
It uses ubuntu as well

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi 

It uses virtual ubuntu and I have removed other things, don't worry

**Comment by MrKrishnaAgarwal** [comment]
the secrets token is fetched automatically from @ericspring08's profile.

**Comment by MrKrishnaAgarwal** [comment]
it's your choice, no worries, feel free to reject this pr

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Will have a review with the changes.

**Comment by MrKrishnaAgarwal** [comment]
> 



> @MrKrishnaAgarwal Will have a review with the changes.

Sure, No worries

**Review by devarshishimpi — COMMENTED** [review]
Preferably make a new PR without the first commit since they get added as unnecessary commits to the project.

**Comment by MrKrishnaAgarwal** [comment]
no unnecessary commits get added only recent commits get added

**Comment by MrKrishnaAgarwal** [comment]
if you want, i can close this pr

**Comment by devarshishimpi** [comment]
> no unnecessary commits get added only recent commits get added

@MrKrishnaAgarwal Please keep in mind that the first commit gets counted towards the project while merging. It has few links which can't be merged. As the requested change which you have done, it looks great to me.

But it gets added while commiting it, Please undo the commits/recreate the fork and only add the second commit. It will merged and your contribution is highly appreciated!

image

**Comment by devarshishimpi** [comment]
> if you want, i can close this pr

@MrKrishnaAgarwal Thank you. You may create a new PR with only the 2nd commit.

**Comment by MrKrishnaAgarwal** [comment]
thanks for reviewing 

bye ✌🏻

**Review by MrKrishnaAgarwal — COMMENTED** [review]
Thanks @devarshishimpi

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Have you requested a new PR for the same? I can't find it as of now

**Pull request closed without merging**
